### ISSUE TITLE
this.auth.sigIn() fails with no server request in JS implementation.

### ISSUE THREAD

**Issue by stimg** [heartsentwined/ember-auth#113]
Ember      : 1.1.0-beta.4 ember.js
Handlebars : 1.0.0 ember.js
jQuery     : 1.10.2 
ember-auth: 9.0.6

There are some inconvenience in JS implementation I've faced to by migration to the version 9.+ (please, correct me if I'm wrong):
- ember 1.0.0 release version doesn't suit to work with ember-auth 9.+ (!Ember.FEATURES), you must upgrade to ember 1.1.+ beta
- there is no way to get modules from your repository, only to install it in Nodejs and dig them out from there (I mean javascript modules)
- modules are not AMD compatible, you must define dependencies for all of them in the shim section if you use requirejs to load js modules
- there are no names for js modules in the docs, you should guess how they was named (I've had luck! :) when you install it for NodeJS

I've managed to get work authRedirectable, but I've stacked with actionRedirectable. I see that modules (`ember-auth-module-action-redirectable` and `ember-auth-request-jquery`) will be initialized, but on auth.signIn() no ajax request happens. I see call ember-auth.js:81 and nothing more. So no request.jquery.singIn() will be performed. What is wrong by me?

Modules Installed:
- ember-auth-module-action-redirectable
- ember-auth-module-auth-redirectable
- ember-auth-module-rememberable
- ember-auth-module-url-authenticatable
- ember-auth-request-jquery

My implementation:

``` javascript

// Enable Ember query parameters feature
Ember.FEATURES['query-params'] = true;

... 

App.Auth = Ember.Auth.extend({
    signInEndPoint: config.api.authorize,
    signOutEndPoint: config.api.authorize,
    baseUrl: config.api.baseUrl + config.api.namespace,
    tokenKey: 'access_token',
    tokenIdKey: 'token_type',
    modules: ['emberData', 'urlAuthenticatable', 'actionRedirectable', 'authRedirectable', 'rememberable'],
    urlAuthenticatable: {
        endPoint: config.api.crossAuth
    },
    rememberable: {
        tokenKey: 'remember_me_token',
        period: config.settings.rememberMeExpires,
        autoRecall: false
    },
    authRedirectable: {
        route: 'login'
    },
    actionRedirectable: {
        signInRoute: 'teams',
        signOutRoute: 'login'
    }
});

App.SecureRoute = Ember.Route.extend({

    authRedirectable: true,

    beforeModel: function () {
        this._super.apply(this, arguments);
    },
    actions: {
        signIn: function () {
            var lc = this.controllerFor('login');


            this.auth.signIn({
                data: {
                    user_id: lc.get('username'),
                    password: lc.get('password'),
                    remember_me: lc.get('rememberMe'),
                    application_id: config.api.applicationId,
                    client_id: localStorage.getItem('clientId') || ''
                }
            })
                .then(function (r) {
                    // If login success
                    console.log('[INFO] SecureRoute: Login success. Auth token: ' + r.token_type + ' ' + r.access_token);
                    $.ajaxSetup({
                        headers: {
                            'Authorization': r.token_type + ' ' + r.access_token
                        }
                    });
                })
                .fail(function () {
                    self.send('showStatusMessage', '_Authorization failed');
                });
        },
        signOut: function () {
            this.auth.signOut();
        }
    }
});

App.ApplicationRoute = App.SecureRoute.extend({...});

```

Tanks a lot for any help!

**Comment by heartsentwined** [comment]
Sorry, they were not designed with AMD/requireJS in mind. #39 mentioned a way of creating them, is that compatible with non-AMD usage?

**Comment by heartsentwined** [comment]
The ember latest dependency was required because you used `urlAuthenticatable`, and it depends on emberjs/ember.js#3182. Otherwise, `ember-auth` will work fine with ember `1.0`.

**Comment by heartsentwined** [comment]
Just to clarify, the `urlAuthenticatable` module has been rewritten. Previously it packed its own solution to handle query params, which required bundling a full `$.url` lib with the module, and a hack hijacking ember's routing process to grab the query params before ember trims them away automatically. Since emberjs/ember.js#3182 introduced official query params support, I have decided to rely on this feature for a cleaner implementation and a smaller code size (the whole `$.url` lib was gone).

**Comment by stimg** [comment]
Thank you for rapid answer! Sorry, maybe I've just packed a lot of unrelated information here. I've resolved issues with AMD. It loads all modules and works with `authRedirectable`. That were just remarks for JS people. Also there are no problems with ember update so far. The most important thing for me now is that `ember-auth-module-request-jquery` doesn't send request to server. Do you have any idea why? I see login page, enter login and password, press OK and get signIn error without any server request.

**Comment by heartsentwined** [comment]
@stimg you can dump the stacktrace from the `.fail()` hook of a promise. [This blog](http://blog.sensible.io/2013/06/10/promise-ate-my-homework-exception.html) describes how a promise could have "eaten up" all kinds of errors, including syntax-semantic errors (e.g. variable undefined - probably a typo). 

``` javascript
doSomething().fail( function() { console.log(arguments); } );
```

My wild guess is that there is no `auth` property directly on `this` - the accessor should have been `this.get('auth')`. This would have thrown a `TypeError`, due to calling an undefined method `signIn()` on `undefined`. Or perhaps some lines in the `.then()` part threw an error - that would end up in the `.fail()` hook too.

Other than these two, I have no idea based on current information.

**Comment by stimg** [comment]
OK, thanks for a tip. I've rolled back to old version now, but will try to solve the issue later, when I have enough time.

**Comment by benperiton** [comment]
I had the same issue, there was an error - "promises.push(get$(this$1, '_session').start(data));"

I added https://github.com/heartsentwined/ember-auth-session-cookie to my app, and it started working. (I didn't add session: 'cookie' to the options, as I don't want persistent data.)

It might be worth noting that you need to include something to handle sessions, I thought it was optional.

**Comment by heartsentwined** [comment]
@benperiton `session: 'cookie'` is the default, so it's still there. But it won't persist anything unless a module requires it. e.g. the `rememberable` module will persist a remember cookie. The `session` component is required because that's where `ember-auth` stores session data - auth token, user id, etc. Now that you mention it, it should be split apart too, that's two concerns lumped together...

**Comment by benperiton** [comment]
@heartsentwined Ah cool, makes sense :)

**Comment by heartsentwined** [comment]
@benperiton does that solve your original problem, whatever it is? (I can't figure it out well what you were referring to in prev comment)

**Comment by benperiton** [comment]
Yep, I just needed to include https://github.com/heartsentwined/ember-auth-session-cookie in my app and it started working

**Comment by stimg** [comment]
I've made a new try to upgrade to last version of ember-auth. Now it works like a charm. The only thing you might fix is replace .fail() with .catch() methods when you work with RSVP.Promise. I get messages  from Ember on console `DEPRECATION: RSVP.Promise.fail has been renamed as RSVP.Promise.catch`
