### ISSUE TITLE
Error running rake dist

### ISSUE THREAD

**Issue by seanrucker** [heartsentwined/ember-auth#26]
After bundle install and running rake dist I get an error:

can't activate rack-1.4.4, already activated rack-1.4.5

Not sure what to do — I tried uninstalling 1.4.5 but other gems depend on it so that doesn't work.

**Comment by seanrucker** [comment]
I got around it for now using a custom gemset.

**Comment by heartsentwined** [comment]
I did a `bundle install` and `rake dist` from a fresh repo clone and it worked fine at my environment. Try this:

# TL; DR

Try `bundle exec rake dist`.

# Details

Some other settings (other rubies? other projects?) are sharing the same gem environment. `rake` might be pointing to somewhere else other than the one intended by `ember-auth`.

Are you using [rvm](http://rvm.io/)? This is the easiest "blackbox" method to handle multiple gem and ruby versions. `create` a gemset for `ember-auth` (and `use` it), and `rake dist` will be run scoped to only the `ember-auth` environment.

Otherwise, appending `bundle exec` in front of commands will force it to use the current `bundle` environment for the command.

**Comment by seanrucker** [comment]
bundle exec rake dist... beauty.

I knew there was a way to run bundle and ensure proper versions but couldn't remember what it was. Thanks!

**Comment by heartsentwined** [comment]
Thanks for this issue anyway, I have added notes to the readme to clarify the steps.
