### ISSUE TITLE
Remember me cookie

### ISSUE THREAD

**Issue by rastasheep** [heartsentwined/ember-auth#36]
Hi, 
I have a problem with remember me feature. 
Followed by instructions in your exemple, everything goes just fine. When i log in, ember-auth creates cookie, when i refresh page, i'am still loged in, but after that first reload, cookie disappears, and after another refresh i'am logged out.

I'am tried  with:

```
rememberMe: true
rememberTokenKey: 'remember_token'
rememberPeriod: 14 # days

##

EmberAuthRailsDemo.ApplicationView = Em.View.extend
  didInsertElement: ->
    Auth.Module.RememberMe.recall()

```

And with

```
rememberMe: true
rememberTokenKey: 'remember_token'
rememberPeriod: 14 # days
rememberAutoRecall: true
```

I also tried with local storage, but same problem occurs.

Is this some bug, or i doing something wrong?

**Comment by heartsentwined** [comment]
Ah. Cookies. This is a divided issue, on many fronts. We are still not sure what the expected behavior _should be_. Read on:

First, do we allow / use _session_ cookies? If so, what should be their behavior? Here is the relevant section from the tutorial discussing on this issue. Model page, [base controller](https://github.com/heartsentwined/ember-auth-rails-demo/wiki/Model#base-controllers) section:

> **Important: Devise's `authenticate_user!` will not work for token authentication.** It will give you "false positives", i.e. letting users through when they aren't authenticated:
> - It redirects users, while we want a `401 Unauthorized`.
> - It does not check for presence of `auth_token`.
> - It allows users to pass a cookie for authentication. This may or may not be the behavior you want. We will consider this in detail.
> 
> The cookie issue is allows users to stay signed in (within any timeout periods set, of course), as long as one does not send a sign out request ("press the sign out button") explicitly. For example, if one simply closes the browser without pressing the sign out button, one will still be considered signed in on the next visit, because the cookie is left behind untouched and it gets sent together in the request, _even though no `auth_token` is sent_. We will tackle both solutions (keep or discard this behavior).
> 
> First, a skeleton `Api::AuthController`, with an `auth_only!` method.
> `app/controller/api/auth_controller.rb`:
> 
> ``` rb
> module Api
>   class AuthController < BaseController
> 
>     protected
> 
>     def auth_only!
>     end
>   end
> end
> ```
> 
> Devise's `authenticate_user!` is not working, but fortunately `user_signed_in?` will give us the correct authentication state. We will render our `401` unless the user is signed in.
> 
> ``` rb
>     def auth_only!
>       unless user_signed_in?
>         render json: {}, status: 401
>       end
>     end
> ```
> 
> The cookie issue: `user_signed_in?` will allow the above-mentioned cookie-based authentication. So, you have already finished the `Api::AuthController` if this is the behavior you want. However, we will use the alternative solution. We will check for the presence of a (valid) `auth_token` on every request, effectively disabling the cookie-based authentication behavior.
> 
> ``` rb
>     def auth_only!
>       unless params[:auth_token] && user_signed_in?
>         render json: {}, status: 401
>       end
>     end
> ```

Second, on _remember_ cookies. What _is_ the expected behavior for these? The first thing to recognize is that, **an immediate browser refresh is no different from re-accessing the app two days later**. The latter case is obvious: we should treat it as a full app-restart. What about the former? Ember correctly tries to serialize and deserialize app state via the URL, but we are venturing past this to `cookie`s / `localStorage`s - the question remains: what _should_ be the behavior for these?

On one hand, we have sites like facebook, github, google, that persists the signed in state past browser refreshes. On the other hand, we have higher-security sites, like e-banking systems, that treats any browser refresh as invalidating any signed in state.

Finally, we have a third issue: treatment of _remember_ cookies on sign in failures. Presumably, the apparent asynchrony of cookies across three refreshes is related to different server response and client expectation. Here is what `ember-auth` does:
1. A sign in, with remember option turned on, and successful server response: store the remember cookie
2. [Refresh / App restart] Now `ember-auth` will look for a remember cookie locally, and _try_ to sign in the user. If the server responds with a failure, it will clear the remember cookie (and the user is not signed in).
3. [branching]
   1. The user tries to sign in as another user, without going through the sign out procedure (your app's UI should disallow this anyway). Regardless of server response, and regardless of the remember setting of the new sign in request, `ember-auth` will clear the remember cookie. Whether a new remember cookie is set depends on remember setting and server response.
   2. [Refresh / App restart] Now there is no remember cookie locally, `ember-auth` will just report a non-signed in state.

One more caveat though: the auto-recall feature will only happen when the user accesses an `Auth.Route`. (No point doing so otherwise, the user is only accessing public content.) So, for example, assuming that a remember cookie is present locally:
1. [branching]
   1. Let's say the user enters the app via a vanilla `Em.Route`. No sign in attempt here.
   2. Or, if the user enters the app via an `Auth.Route`, a sign in will be attempted immediately.
2. The user continues browsing public `Em.Route`s. No sign in attempt.
3. The user accesses an `Auth.Route`. Sign in attempt (if not already signed in).

Among all these, it is of course also possible that userland code can interfere / change the logic, e.g. with redirects, with manual calls to `Auth.Module.RememberMe.*` methods, etc.

Hope this helps you understand what's happening.

Due to the above-mentioned issue of not having an agreement on expected behaviors, if you think you have found a bug, please first describe what you think the expected behavior _should_ be. Then we can discuss if this should indeed reflect the majority use case.

**Comment by rastasheep** [comment]
Thanks for this long, answer :)

I think that server side is ok, because on sign-in i get remember me token, and prevent unauthenticated  user to see what i don't allow to him.

Second i agree that browser refresh is no different from re-accessing the app two days later, and with that on mind i tried to reproduce github like sessions (no meter on what, user stays logged in, by that i mean refresh, restart of browser etc.).

The best case it would be that we have rails like session, when user sings in, session starts, but after closing browser sessions disappears. I think that is hard to reproduce, and i would be happy with github like session (if there is cookie user is signed in, after cookie expires or user manually logs out , session is ended).

After few times of reading what actually ember-auth does, it coms to my mind that "public routes" are problem.

Here is my workflow:
- A sign in, with remember option turned on, and successful server response, cookie/localStorage is stored (i'am using widget style sign in form, if is there any diference)
- [Refresh / App restart] On public route, ember-outh detects cookie, and logs me in (public page)
- After this login success, cookie that is used for login in step 2. no more exists 
- [Refresh / App restart] Again, because there is no cookie, i'am not loged in anymore (public page)

Conclusion, i want to have application wide logged in user thill he don't sign out manually.

**Comment by heartsentwined** [comment]
Widget-style vs Full-page-style templates do not make a difference.

Your workflow is a solid use case, but I have one slight complaint:
1. (signed in with remember)
2. [restart] auto sign in
3. and deletes cookie <-- here, why?

I think this workflow would be counter-intertuitive to most users: let's say a user saw an option "Remember me for two weeks" on the sign in page.
1. He turns remember me on, signs in, does some work, and closes browser (without signing out).
2. Two days later (i.e. within the remember period), he comes back, is signed back in automatically, and he is happy.
3. The third day (still within the remember period), he comes back, now he is not signed in (because cookie is deleted). Why?

(This described behavior contradicts with your conclusion "I want to have application wide logged in user thill he don't sign out manually".)

I would not like to make an assumption on your app's use case, but I disagree that deleting the cookie would be the expected behavior. For this reason, this would not be implemented in `ember-auth`.

Regarding enabling sign in for public pages. Whether this should be done depends on the app. I guess your app is heavy on protected pages, so it would make sense for your case. However, if another app is heavy on public pages, then most of the time the user would not even need to sign in. For this reason, this would be an optional behavior, at best, not a default behavior.

Finally, there is a issue of when the sign in attempt should be performed. For the `Auth.Route`, the loading of the ember app is halted for the sign in to complete (or fail), and then the user is either granted access to the protected content, or `ember-auth` notifies userland code that the user is trying to access `Auth.Route` without a valid action. This makes sense because it is necessary for the user to be signed in in order to view the protected content correctly.

However, the opposite is true for public pages. A sign in would not aid the user immediately. For this reason, I would almost surely not implement the same behavior as the `Auth.Route`, at least not as the default. A more sensible approach would be to let your ember app load faster, and does the (not immediately important) sign in work afterwards in background. This approach can be implemented thus:

``` coffeescript
App.ApplicationView = Em.View.extend
  didInsertElement: ->
    Auth.Module.RememberMe.recall()
```

This performs the sign in attempt _after_ ember has finished rendering the initial page's contents. Userland code will be notified of sign in status via [standard events](https://github.com/heartsentwined/ember-auth#events), and you can implement the same visual changes / notifications for the user via standard hooks to `if Auth.authToken`.

As for your use case of clearing the cookies after a public route visit, do this:

``` coffeescript
App.ApplicationView = Em.View.extend
  didInsertElement: ->
    Auth.Module.RememberMe.recall()
    Auth.Module.RememberMe.forget() # after the sign in attempt
```

Thank you again for pointing out this use case to me, I'll get this optional feature implemented in `ember-auth` soon (except the delete cookie part).

**Comment by rastasheep** [comment]
Sorry, workflow that wrote is what happend to me, not what i want to achieve.

I tried with:

```
App.ApplicationView = Em.View.extend
  didInsertElement: ->
    Auth.Module.RememberMe.recall()
```

But it only works only _once_, after that automatic sign in, cookie disappears.

**Comment by heartsentwined** [comment]
That would be a bug. I'll look into it.

**Comment by rastasheep** [comment]
One more thing, remember me on your example app (http://ember-auth-rails-demo.herokuapp.com/), doesn't work too.

**Comment by heartsentwined** [comment]
Thanks, I'll look into it.

**Comment by heartsentwined** [comment]
Several issues addressed in the latest commits:
1. remember me is now working correctly as you expected. (cookies not getting deleted "accidentally".)
2. the demo app is working now.
3. about your use case of remember-me for public routes:

This feature has been added to `ember-auth`. It enables the auto-recall feature from remember me module on regular `Em.Route`s, via a config flag:

(section from [readme](https://github.com/heartsentwined/ember-auth#url-authentication)):

> By default, url authentication is only available on `Auth.Route`s. If you
> want it to be available for regular `Em.Route`s too, set:
> 
> ``` coffeescript
> Auth.Config.reopen
>   urlAuthenticationRouteScope: 'both' # defaults to 'auth'
> ```

Now you can have users auto signed in, even if they are on a public route.

Please refer to the readme for detailed docs.

**Comment by rastasheep** [comment]
Great, thanks for quick response,
i'll test it and if there is some issues i will post them.

**Comment by rastasheep** [comment]
Works like a charm! 
Thanks again.

**Comment by heartsentwined** [comment]
Glad to help :smile:
