### ISSUE TITLE
How to make ember-auth work with RequireJS

### ISSUE THREAD

**Issue by deepcloud** [heartsentwined/ember-auth#39]
I'm trying to use shim to load "ember-auth.js", but looks like it doesn't work, any ideas? Thanks,

FY

**Comment by heartsentwined** [comment]
My apologies, `ember-auth` was not designed with RequireJS in mind. I would be glad to include this support in the next release. Any pointers on writing a RequireJS-compatible module?

**Comment by heartsentwined** [comment]
@deepcloud the latest version (`6.x`) of `ember-auth` now attaches itself to the `Ember` namespace as `Ember.Auth`, instead of using its own global `Auth`; furthermore, you now instantiate your own app-specific copy of `ember-auth` through `App.Auth = Ember.Auth.create({})`, so in userland code `ember-auth` would live within your App's namespace too.

I assume that you have already got `ember` to work with RequireJS somehow, so perhaps `ember-auth` would now "just work"? I myself haven't had any success in getting `ember` itself to load via RequireJS, so I am not sure. Otherwise, can you show me how you got `ember` to work with RequireJS? I can then have a working example, and I can follow ember's solution and implement it in `ember-auth`.

**Comment by heartsentwined** [comment]
Closing. Assuming either that `ember` works with RequireJS, and `ember-auth` will work also by attaching itself to the `Ember` namespace; or that both won't work (in this case, `wontfix` because `ember-auth` depends on `ember` anyway).

**Comment by Chandler** [comment]
You can create a require.js module for ember-auth like this, note that it will still be on the global namespace as well so this may or may not be useful to you.

``` javascript
define('ember-auth', ['ember'], function (Ember) {

 . . . ember auth source

return Ember.Auth
}
```

As was mentioned earlier this assumes you have ember, jquery, and handlebars setup as require.js modules as well. An ember require.js module looks like this.

``` javascript
define('ember', ['jquery','handlebars'], function ($,Handlebars) {

. . . ember.js source

 return Ember;
});
```
