### ISSUE TITLE
Error during the mixin with Auth.SignInConrtoller

### ISSUE THREAD

**Issue by 90rdon** [heartsentwined/ember-auth#40]
Ember-Auth doesn't seem to redirect the user after authentication with the default routing. I know I got the "authToken" and "currentUserId" from the server, but the user did not get redirected and reminded on the "sign in" page. Then I followed your instructions with mixin in the Auth.SignInController to do customize redirecting, except I got these errors from the browser debug during page load, "Uncaught Error: assertion failed: Expected hash or Mixin instance, got [object Function]" and "Uncaught Error: assertion failed: The route signIn was not found". Here is my Gist - https://gist.github.com/habit-us/5460752. As soon as I removed the Auth.SignInController mixin, the error went away, but still no redirecting. 

Can you please help? I am stuck for a few days now. I appreciate any of your help.

**Comment by heartsentwined** [comment]
First, make sure the route `signIn` is actually defined in your router. Something like:

``` coffeescript
App.Router.map ->
  @route 'signIn'
```

Note also that a `controller` is different from a `view`. Defining `templateName` on the `controller` will not hook onto that handlebars template; it will just sit there (and be a Property of the controller). Instead, you probably mean:

``` coffeescript
App.SignInView = Em.View.extend
  templateName: 'signIn'
```

\- along with the corresponding handlebars template. For easy debugging, I would explicitly write up the full set of `route`, `controller`, `view`, `template`, so that I can control what's in them.

Otherwise, could be related to #29, #42 .

**Comment by heartsentwined** [comment]
Assuming issue fixed due to inactivity. Please reopen this ticket @octapus if the issue persists.
