### ISSUE TITLE
Redirect logic does not work for routes with a context

### ISSUE THREAD

**Issue by seanrucker** [heartsentwined/ember-auth#42]
For example, take the following URL: http://www.example.com/#/posts/5

If a user tries to access that URL before he has authenticated ember-auth will store the route name and transition to the sign-in route:

```
if Auth.Config.get('authRedirect')
  Auth.set('prevRoute', @routeName)
  @transitionTo Auth.Config.get('signInRoute')
```

The route name does not include the post id and therefore after successfully logging in the redirect logic will transition to /#/posts instead of /#/posts/5

I'm not sure what the solution is yet — I'm opening this ticket to get some discussion started.

**Comment by heartsentwined** [comment]
I got a solution in the pipeline, working to get it fixed. Basically, the current implementation falls apart on routes with dynamic segments, because when it tries to transition back, the model will be missing. Unfortunately, it's quite a grosteque fix, with lots of access to supposed private methods, due to ember keeping a whole bunch of routing necessities protected (the `params` passed in the model hook, for instance). I'll push it upstream once I get it done, should be within two or three days

**Comment by heartsentwined** [comment]
See discussion on #29, specifically [this write up of mine](https://github.com/heartsentwined/ember-auth/issues/29#issuecomment-17048375).

**Comment by heartsentwined** [comment]
@seanrucker the `5.x` version fixes this bug.
BC breaks in `5.x` version is rather dramatic, hence I haven't written an upgrade guide yet. The [docs](http://ember-auth.herokuapp.com) should help you upgrade; otherwise please feel free to ask me how to convert a specific usage.
