### ISSUE TITLE
Ember Model compatibility

### ISSUE THREAD

**Issue by kevinansfield** [heartsentwined/ember-auth#53]
Are there any plans to support libraries other than Ember Data such as Ember Model (https://github.com/ebryn/ember-model)?

Is this something that would be possible to override in-app rather than in the ember-auth library?

**Comment by jiripospisil** [comment]
I was trying the very same thing yesterday and came up with this: https://gist.github.com/mekishizufu/5582787 It patches the RESTAdapter that Ember Model ships with and seems to work fine. I am not happy with the amount of code it duplicates but it's probably good enough for now.

**Comment by heartsentwined** [comment]
Spot on @mekishizufu.

Long story: there are only two `ember-data`-related pieces of code in `ember-auth`.

First, the patching of `ember-data`'s `DS.RESTAdapter`. Basically, we just have to route all adapter requests through `App.Auth.send(settings)`. With the default `jQuery` `requestAdapter`, `settings` would be the params for `jQuery.ajax(settings)`. The `emberData` module just normalizes the call from `ajax(url, type, settings)` to `ember-auth`'s expected `send(settings)`. @mekishizufu did the same normalization for Ember Model. However, I confess that I am not familiar with Ember Model; you would have to make sure that patching `Ember.RESTAdapter._ajax()` is enough for _all_ requests (at least all that you want authenticated) to be routed through `App.Auth.send()`.

The second piece of code is the expected `App.UserModel.find(id)` API on your user model, if you elect to let `ember-auth` auto-load the current user instance. This is not exactly `ember-data`-specific; I have just adopted its convention.

As for merging this into `ember-auth`, for now I'd say no, because the readme over at Ember Model explicitly states that the future of that project is to deprecate itself in favor for `ember-data`. Unless we have more use cases for Ember Model, we'll just let devs use @mekishizufu's gist here.

**Comment by jiripospisil** [comment]
> However, I confess that I am not familiar with Ember Model; you would have to
> make sure that patching Ember.RESTAdapter._ajax() is enough for all requests
> (at least all that you want authenticated) to be routed through
> App.Auth.send().

It should be _as long as_ your model uses the RESTAdapter adapter - in Ember
Model every model might use a different one. Often you want to make a custom
ajax request or your own adapter (legacy APIs etc.) and in that case you need to
use the `App.Auth.send` method instead of the usual `Ember.$.ajax` as stated 
above.

> The second piece of code is the expected App.UserModel.find(id) API on your
> user model, if you elect to let ember-auth auto-load the current user
> instance. This is not exactly ember-data-specific; I have just adopted its
> convention.

This works fine as Ember Model tries to mimic Ember Data's APIs. In fact, I am
already using pretty much all of the default modules without any problems.

**Comment by heartsentwined** [comment]
You're the Ember Model expert here :smile:

**Comment by heartsentwined** [comment]
Closing issue (`won't implement`) unless Ember Model gathers more users, or it no longer declares to deprecate itself in favor of Ember Data.

**Comment by darthdeus** [comment]
I think Ember Model should be part of ember-auth, just because it is the go-to solution for anyone not using Ember Data. It also doesn't have the deprecation notice anymore :)

Here's a sample implementation of Ember Model module for the Ember.RESTAdapter https://gist.github.com/darthdeus/286a0ad56fce37261761 and JS counterpart https://gist.github.com/darthdeus/615a2708734894680c54

I wanted to make a PR, but there's no ember-model-source gem, so I'm not sure how to proceed there.

**Comment by heartsentwined** [comment]
I just checked, the deprecation notice is still there

> The goal is someday everyone's JSON APIs will be conventional enough that Ember Data will be the best choice of data library for Ember. Until then, Ember Model will make it easy to get up and running quickly with Ember.

The folks over at `ember-data` are also working on [`json-api`](https://github.com/json-api/json-api), so overall I think `ember-data` is working towards the scenario described above.

I have nothing against Ember Model specifically, just that it declares to deprecate itself in favor of Ember Data, and I question the wisdom of including support for a library that is known to deprecate.

**Comment by heartsentwined** [comment]
Lack of `ember-model-source` gem is not an obstacle though, since the module is off by default, so we can trust that anyone who actively chooses to enable the module should know what he is doing (and have built and included the Ember Model library). In any case, I see that you have put a guard clause checking for the existence of `Ember.RESTAdapter` also.

**Comment by imanel** [comment]
I hope that you are aware that this is ironical statement and they have no plans to deprecate it right? There is no way that all API's will be build under one convention, and without that Ember Data is hard to work with. I would also ask for support for Ember Model - looks like @darthdeus path should work.

**Comment by ebryn** [comment]
Ember Model isn't going anywhere.

**Comment by trek** [comment]
With `ember-data` moving forward with [`json-api`](http://jsonapi.org/) there even more of a need for `ember-model`. You'll always need a library for existing projects or projects where the UI engineer can't mandate the serialization format.

`ember-data` will rock for greenfield projects, but that's not the world I get to live in (sadly).

**Comment by heartsentwined** [comment]
Sorry folks, I didn't realize that was a sarcasm on the `ember-model` docs. Anyway, @darthdeus has the correct solution in his [gist](https://gist.github.com/darthdeus/286a0ad56fce37261761) posted [above](https://github.com/heartsentwined/ember-auth/issues/53#issuecomment-18447051). Do you want to submit a PR yourself (and take credit)? My implementation would probably be exactly the same.

**Comment by heartsentwined** [comment]
Implemented (on master). It's a bit different from the implementation of @darthdeus, in that I added the promise callback logic that is present by default in the ember-model library.
