### ISSUE TITLE
CSRF?

### ISSUE THREAD

**Issue by brandonparsons** [heartsentwined/ember-auth#61]
Good afternoon,

I have been doing some pondering about client side interactions with server side authentication, and how that ties into `ember-auth` and `ember.js`.

Given that the `auth_token` is passed to the Rails API on each request, is CSRF protection still required? (Assume that the original authentication is completed using SSL and no XSS vulnerability exists).

Given that an ember app can be distributed as static HTML/JS, I'm wondering if I still need Rails to generate CSRF tokens for me.  Or do I not need to worry about it?  I'm assuming the `auth_token` is stored in the JS runtime, so would not be accessible from 3rd parties even if you were logged in?

**Comment by heartsentwined** [comment]
Good question. I pondered upon the same question myself when I started writing `ember` apps. I believe that there is no definite answer, so here are several angles (in no particular order):

# Rails as API

Your server now acts as an API. Essentially you _want_ to allow access to your API from anywhere (because people can access your ember site from anywhere). I'll quote myself from the [security](https://github.com/heartsentwined/ember-auth/wiki/Security#secure-server-side-api-code) page:

> You should treat your ember app as a fancy UI for your server's API service, and implement validations and security checks server-side, much like you should never rely on client-side data validation.
> 
> Think of it this way: some of your API endpoints is protected, and needs an authentication token to consume. `ember-auth` does nothing more than providing a convenience method for users to obtain this token, in order to consume your protected API endpoints.
> 
> The bottom line: **Anybody** can consume your API service, not only your ember app.

You can do something else to this policy, e.g. limit to certain IPs if you are making an internal admin interface, etc, but that varies by use case.

# Auth token accessibility

Ember is a client-side library. _Anybody_ can access your `auth_token` - and everything else in your app, for that matter. For instance, what's there preventing a user from opening a console, and calling `App.Auth.get('authToken')`?

A minor point is that, this information is not in the static files (but your ember app is).

# Rails CSRF

I assume that you are familiar with rails' original CSRF. Otherwise, read [the docs](http://guides.rubyonrails.org/security.html#cross-site-request-forgery-csrf).

# Re-implementing a CSRF?

You can certainly do so. Several things to consider:
- This obviously can't be inserted into the html files if you are using static assets, or if you are serving assets from a dedicated server.
- Or, make your app `GET` an API end point, no matter what, after initialization, such that your server can send back a CSRF token? Or perhaps it will come along with your other API responses in the headers?
- Do you want a _refreshing_ CSRF token, that will change after each API usage?
- But ember may send several API actions at the same time.
- Rails' CSRF is session-based. We are using token authentication now, so session is gone. To prevent indefinitely-valid CSRF tokens, perhaps you would want to timeout the user after some set period of time? (In this case, do you want a `timeoutable` module in `ember-auth`?)
- Or timeout the user after some period of inactivity? (And the server has to `push` to the client to notify it of this change.)
- Amidst all this, are you having another frontend for your app/API? e.g. an `ember` website for web interface, and a `phonegap` app for native mobile apps? In this case, you'll have to either implement CSRF on all these interfaces, or none at all. After all, rails is now an API server.

**Comment by brandonparsons** [comment]
Thank you very much for the detailed reply!

I have certainly learned a lot over the last few days trying to read up on
CSRF and figure out what I should be worried about.  I think the two most
important realizations I've had (and you mentioned them below) are:
- Using Rails strictly for the API -- you **want** to be able to hit the
  service from anywhere, not just from your website.  Seems like an obvious
  point, but easy to get lost in the CSRF forest.
- Requiring token authentication (and turning off stateful cookies in the
  Devise token_authenticable module -- is this required ? -- ) eliminates the
  risk of malicious CSRF against the API.  You should be using SSL to prevent
  attackers listening in, and in that case you do not have an authentcated
  cookie for the attacker to rely on.  (i.e. They can't fake a call to POST
  /my-account/transfer?dollars=onemillion&to=hacker as they won't have the
  auth_token and it is used on every request).

I'd appreciate your input on the 2nd point to make sure I am not off the
deep end.  Is there a way to explicitly tell Rails/devise to not set a
session cookie?  Or am I on the right track with just turning off stateful
cookies? That being said, I still might end up using the standard Rails
view / HTML stack for some admin backend or pages associated with my
application, so I've been thinking about how to force CSRF protection on
the Rails view layer, but turn it off for API requests.  I'm thinking that
using cookies for standard logins and tokens for API requests has me
covered, but I'm not 100% sure.

**Comment by heartsentwined** [comment]
Cookies. How you want them to behave is again a matter of preference and individual app use case. I did a (not too deep) write up in the [tutorial](https://github.com/heartsentwined/ember-auth-rails-demo/wiki/Model). In short:

> [The default] allows users to pass a cookie for authentication. This may or may not be the behavior you want.

**Comment by brandonparsons** [comment]
Thanks for writing this all up.  I think I have a much better handle on this now.
