### ISSUE TITLE
ActionRedirectable

### ISSUE THREAD

**Issue by asia653** [heartsentwined/ember-auth#69]
Has this been broken from the last few patches?

Using it, if I want to go to a direct route in my application(/#/events) via a new tab in the browser or a refresh, the application has to reauthenticate me via remember_token(which makes sense, no session exist in api app).

Since it reauthenticate me, actionredirectable redirects me back to my 'home' route and that breaks the html layout.

**Comment by asia653** [comment]
You can slightly reproduce this via the sample application here: https://github.com/joscas/base_app

Signup with a user.
Signout.
Signin with remember me enabled

Open a new tab in your browser and paste in https://starter-app.herokuapp.com/#/users/
EmberAuth will redirect us to the home route because we got just authenticated in the new tab, but you'll also see a list of the users. Is this intended behaviour?

**Comment by joscas** [comment]
Upps. That is not the expected behavior at all... Let me investigate this.

**Comment by joscas** [comment]
First af all, let's make clear that my demo base-app is not the official demo application for ember-auth. Also the online version is not running with the latest version of ember-auth. I was waiting for the next version of ember-auth to upgrade because I assume it will work with the new router version of ember.
Finally, since the list of signed-up users is something that shouldn't be public, I've taken down the application until the problem is solved. This means that you won't be able to reproduce the situation unless you install you clone the repo locally.

**Comment by joscas** [comment]
In any case, the backend should never return the list of users for a non admin user. So at list this problem is partially related to a bug which has nothing to do with ember-auth.

**Comment by asia653** [comment]
I am aware that of the security problem but were you able to reproduce the redirect bug that this ticket was originally intended for?

**Comment by heartsentwined** [comment]
We'll wait for status update from @joscas for this issue; in any case I'm working with the rc6 upgrade now (current version will simply break) so this'll have to wait.

**Comment by joscas** [comment]
I'll work on a fix for the backend security in my example app but won't test the redirection problem until we have an ember-auth upgrade for rc6. It looks like this upgrade will solve important issues and I think it's worth being patient and letting @heartsentwined do his part.

**Comment by heartsentwined** [comment]
`7.x` branch now released, with rc6 (new router!) support. [changelog](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md), [upgrade guide](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide), [docs](http://ember-auth.herokuapp.com/docs) and [demo](https://github.com/heartsentwined/ember-auth-rails-demo/) all properly updated. Main notes:
- `ember-auth` now _requires_ ember `rc6` or above
- the new router now _encourages_ you to use `authRedirectable` as "the ember way" of solving auth-only routes (with auth-only models)
- thus you might want to pair it with `actionRedirectable` too for user experience
- despite this being a major version update, it would likely not break most userland code; the BC breaks are not in main, documented API

**Comment by kevinansfield** [comment]
I'm not sure if this is the same issue but since upgrading to `7.0` when I directly access a route (via url/refresh) that includes `authRedirectable` and I have a valid remember_me cookie I am re-authenticated but redirected to the route specified in `signInRoute`.

Previously, accessing one of these routes would error as it tried to access restricted server routes without a token so it has definitely improved upon that but I was expecting with the new router that you'd stay on the same route.

My auth config is as follows:

```
App.Auth = Ember.Auth.create

  tokenKey: 'auth_token'
  tokenIdKey: 'user_id'
  userModel: 'App.User'

  signInEndPoint: '/users/sign_in'
  signOutEndPoint: '/users/sign_out'

  modules: [
    'emberData',
    'rememberable',
    'urlAuthenticatable',
    'authRedirectable',
    'actionRedirectable'
  ]

  rememberable:
    tokenKey: 'remember_token'
    period: 14 # days
    autoRecall: true

  urlAuthenticatable:
    paramsKey: 'auth'

  authRedirectable:
    route: 'home.sign_in'

  actionRedirectable:
    signOutRoute: 'home'
    signInRoute: 'newsfeed'
    signInSmart: true
    signInBlacklist: [
      'home',
      'home.sign_in',
      'home.confirmation_required',
      'sign_out'
    ]
```

**Comment by asia653** [comment]
About to test 7.x but @kevinansfield seems to have the same issue.

**Comment by asia653** [comment]
Mangled template fixed. Awesome work on the new release @heartsentwined.

@kevinansfield, I am getting the same "issue"(if it can be called that). Might be expected behaviour. For now, I'm closing this because the problem originally referenced has been fixed.

**Comment by heartsentwined** [comment]
@kevinansfield @Edwardzyc I cannot reproduce the (new) [issue](https://github.com/heartsentwined/ember-auth/issues/69#issuecomment-20345835). The [demo app](https://github.com/heartsentwined/ember-auth-rails-demo) does have such a set of routes (the `users` set). They are all `authRedirectable` enabled. The `actionRedirectable.signInRoute` is set to `users`. `rememberable` is enabled. However, when I access `/users/1` directly via the browser (with a remember cookie), it does _not_ get redirected away to `users`; it stays on `/users/1`.

(The `undefined` in the URL is another issue reported in heartsentwined/ember-auth-rails-demo#6.)

For now this issue stays closed, unless we can reproduce the new described observation.

**Comment by kevinansfield** [comment]
Minor update on the above - I haven't been able to fix the problem yet but I have found that the redirect is happening on any route, even those not using the `AuthRedirectable` mixin.

**Comment by kevinansfield** [comment]
@heartsentwined @Edwardzyc I managed to fix the redirect issue. It turned out to be the order of the modules defined in `Ember.Auth.create`.

before:

```
App.Auth = Ember.Auth.create
  modules: [
    'emberData',
    'rememberable',
    'urlAuthenticatable',
    'authRedirectable',
    'actionRedirectable'
  ]
```

after:

```
App.Auth = Ember.Auth.create
  modules: [
    'emberData',
    'urlAuthenticatable',
    'authRedirectable',
    'actionRedirectable',
    'rememberable'
  ]
```

**Comment by asia653** [comment]
Looks like order does count. Thanks @kevinansfield and @heartsentwined 
Great base app @joscas

**Comment by heartsentwined** [comment]
Order _does_ count. Multiple modules might want to do the same mutually exclusive action. An example: you have `rememberable` and `urlAuthenticatable` on, someone already has a remember cookie saved, but now this guy accesses your app with a URL with auth token. Which should take precedence (hence overriding the other sign in attempt)? That's completely up to userland; both might make sense given the use case.

**Comment by heartsentwined** [comment]
The use case of @kevinansfield:

`actionRedirectable` needs to register the transition in order to have somewhere to redirect to - otherwise it will use the specified fallback route.

The "before" case

``` coffee
App.Auth = Ember.Auth.create
  modules: [
    'emberData',
    'rememberable',
    'urlAuthenticatable',
    'authRedirectable',
    'actionRedirectable'
  ]
```

Now `rememberable` completes the sign in before `actionRedirectable` registers a route. But `actionRedirectable` does receives a sign in redirect request, so with no route, it redirects to the fallback route.

The "after" case:

``` coffee
App.Auth = Ember.Auth.create
  modules: [
    'emberData',
    'urlAuthenticatable',
    'authRedirectable',
    'actionRedirectable',
    'rememberable'
  ]
```

Now `actionRedirectable` finishes registering the transition redirect, then `rememberable` signs in, so now `actionRedirectable` has somewhere to redirect to.

I hope this clears the matter up.
