### ISSUE TITLE
signOut not sending token

### ISSUE THREAD

**Issue by ralfschimmel** [heartsentwined/ember-auth#71]
I am using token authentication and everything works as expected in 7.0.0 except the signOut.

It sends a DELETE to the specified endpoint but it does not send the token. Without the token the sever cannot identify the user and thus cannot terminate the session.

Is this a bug or is it by design?

**Comment by heartsentwined** [comment]
Are you signed in in the first place? The [demo app](http://ember-auth-rails-demo.herokuapp.com/) is working as expected - I manually inspected the sent payload, and the auth token is there. What ember-auth does, is that it serializes the existing session into a payload to be sent to the server. The default uses `token` as the `strategyAdapter`, so it will put the auth token in one of the params by default. Unless you have configured `tokenLocation` otherwise, that is. (`authHeader` or `customHeader`, where they will appear as an Authorization header or your custom header respectively.)

If there is no auth token anywhere, then - if not a bug - this indicates that there is no session in the first place, so there is nothing to serialize. As a test, you can first go to the same environment where you had wanted to do `signOut()`, then try making your app request the server for, e.g. a model (by visiting a route that has not been visited before, or just `App.SomeModel.find()`). Behind the scenes ember-auth uses the same serializer for this request, and if there is a signed in session, the token should appear in this model request too, even if the model is not auth-only.

**Comment by ralfschimmel** [comment]
Strange enough, yesterday my tests failed, today they succeed, will close this issue.
