### ISSUE TITLE
Let the store wait until accesToken is requested

### ISSUE THREAD

**Issue by kersten** [heartsentwined/ember-auth#8]
Hello,

I have a problem regarding ember-auth. I setup my complete app with all Auth routes, etc. But if I open a Auth.Route directly the router tries to load a Model.find(). The problem is that the authToken is not there yet and therefor the server rejects the request, because there is no backend match with the current session accessToken.

Another problem is the redirection to the sign_in route if I try to open up a Auth.Route directly with no model extended. The router does what he should, he redirects me to sign_in route, but then the accessToken is requested and my session is valid, because I am already logged in.

Is it possible to wait with all redirects and initializing states till the authToken is checked?

Greetings Kersten

**Comment by heartsentwined** [comment]
The first issue. This is the expected behavior of `Auth.Route`. It does nothing by default, it's there to provide a central place for auth-related tasks. If you use `ember-auth`'s redirection, then `Auth.Route` does redirect away before trying to `Model.find()`. Otherwise, if you want to short-circuit the route, use the event hook `authAccess`:

``` coffeescript
App.SecretRoute = Auth.Route.extend
  init: ->
    @on 'authAccess', ->
      # do something

  model: ->
    App.Secret.find()
```

This event will get fired before any redirection, including `ember-auth`'s; this also means that you can implement, for instance, your own redirection logic inside the hook. Technically, it is implemented as the first method call inside `Ember.Route`'s `redirect` hook.

This is designed such that you can possibly show some meaningful content to non-authorized users. Perhaps a popup sign in box? Or an "overview" of the underlying "auth-only" data? Or just a friendly message of "unauthorized area. please sign in." - etc.

For the second issue, I'm not clear about what you mean. Is the user already signed in in the first place? Then he should be able to access the `Auth.Route`. If not, then he gets redirected to your `sign_in` page, - and I'm confused here: is he doing an explicity sign in, or there is somehow already a valid signed in session that is auto-requested?

`Auth.Route` should not care about whether your route has a model or not, all it does is implementing the `redirect` hook of `Ember.Route`. This is the code at the time of writing:

``` coffeescript
Auth.Route = Em.Route.extend Em.Evented,
  redirect: ->
    if !Auth.get 'authToken'
      @trigger 'authAccess'
      if Auth.Config.get 'authRedirect'
        Auth.set 'prevRoute', @routeName
        @transitionTo Auth.Config.get('signInRoute')
```

It checks for signed in state, triggers `authAccess` event, and does a redirection if you enabled it. If the user is already signed in, nothing should happen; the entire code block above should be skipped.

**Comment by kersten** [comment]
Hello heartsentwined,

thanks for you answer. I will try to describe my problem a bit more detailed.

The user comes to my site. It is his first visit. If he clicks somewhere an auth is needed he gets redirected to `sign_in`. So far, so good. Then he logs in and gets his access and remember token. The remember cookie is set and on every `Model.find()` request the `auth_token` is set.

The server saves the access token and validates it on every `Model.find()` request. Now, if the user is on a `Auth.Route` enabled route all data is displayed like it should. But if he hits F5 to refresh the site he will be redirected to the `sign_in` page. After he has landed on `sign_in` `ember-auth` will request `/users/sign_in` because of the saved remember cookie. The answer from the server is a `200 - OK` because the `remember_token` is still valid. Then my navigation gets rendered again an the the Sign In button will be transformed into a Sign Out button. This happens so fast that you will only see a short flickering where the Sign In/Out button resides. After that he has to manually navigate back, where he expected to land.

I hope you understand what I mean. Do I use your lib right?

I have got another problem in the same context. The user logs in and navigates to his account page. All his data is displayed correctly, but if he hits F5 to refresh he gets redirected to `sign_in` like I wrote above, but the `Model.find()` in the accounts `setupController` will also be fired and returns a `401 - Not authorized` because the `access_token` parameter is missing. Only moments later it is there, because of the `/users/sign_in` stuff from `ember-auth`.

I would expect that `ember-auth` validates it's login state and then call all the `Model.find()` with the correct `access_token` parameter. Or accordingly to your answer, at least I would expect that I get redirected to `sign_in` and not that the `setupController` is executed if the user is not logged in (`ember-auth`  does not have the logged in state).

Greetings Kersten

**Comment by heartsentwined** [comment]
Thanks for your detailed description. Can you post your `Auth.Config` settings? i.e. the object you passed to `Auth.Config.reopen()`.

**Comment by kersten** [comment]
Sure, here it is:

```
Auth.Config.reopen({
    tokenCreateUrl              : '/users/sign_in',
    tokenDestroyUrl             : '/users/sign_out',
    tokenKey                    : 'auth_token',
    idKey                       : 'user_id',
    rememberMe                  : true,
    rememberTokenKey            : 'remember_token',
    rememberPeriod              : 14,
    signOutRoute                : 'sign_out',
    smartSignOutRedirect        : true,
    signOutRedirectFallbackRoute: 'home',
    signInRedirectFallbackRoute : 'account',
    signInRoute                 : 'sign_in',
    smartSignInRedirect         : true,
    authRedirect                : true
});
```

**Comment by heartsentwined** [comment]
Thanks, I'll look into the issue and update you here.

**Comment by heartsentwined** [comment]
Rather tricky issue, it's taking more time than I thought, but I would certainly like to implement it.

Marked as enhancement.

**Comment by kersten** [comment]
Many thanks. What do you think how long does it take you to implement it?

**Comment by heartsentwined** [comment]
I'm digging through ember docs throughout these days. The bottleneck is changing from async logic to sync logic.

The original design was to utilize ember's auto-update bindings, such that on `Auth.authToken` checks (and similar logic), the initial state is intentionally left as "non-signed-in". The app is expected to start as non-signed-in, and then ember would update the relevant parts when the user signs in.

On `F5` and other hard-refresh instances, the ember app starts anew, and the challenge is to find something like a "pauseExecute" method to stop ember from loading the app, and then resume once the (async) ajax has completed.

**Comment by heartsentwined** [comment]
My apologies for the delay; I have implemented an auto-recall feature for the remember me function, which should solve your issue. Just update `ember-auth` to the latest version; there is no need to change existing code, although you no longer need to call `Auth.Module.RememberMe.recall()` in userland code.

I have documented this new behavior in the readme, but in short, `ember-auth` will now restore user session whenever one visits an `Auth.Route`, whether internally through interacting with the ember app, or externally via a direct URL entry point (your `F5` use case).

Many thanks for opening this issue, @kersten, your described expected behavior is indeed what is considered the norm for a remember-me feature, and it should, as you said, be expected as the default behavior.
