### ISSUE TITLE
Bundler.require doesn't require EmberAuth (ember-auth-source gem)

### ISSUE THREAD

**Issue by lagartoflojo** [heartsentwined/ember-auth#82]
I'm not familiar with how gems work internally, but I needed to access EmberAuth::Source.bundled_path, and found that EmberAuth wasn't getting included automatically, and had to instead be included with `require 'ember-auth/source'`:

```
$ bundle exec irb
irb(main):001:0> Bundler.require
=> [ (...), <Bundler::Dependency type=:runtime name="ember-auth-source" requirements="~> 7.0">]
irb(main):002:0> EmberAuth
NameError: uninitialized constant EmberAuth
    from (irb):2
    from /home/hernan/.rvm/rubies/ruby-2.0.0-p195/bin/irb:13:in `<main>'
irb(main):003:0> require 'ember-auth/source'
=> true
irb(main):004:0> EmberAuth
=> EmberAuth
```

**Comment by heartsentwined** [comment]
I am not a bundler expert either, but from what I see with other gems, this is the expected behavior. The gem is called `ember-auth-source`, so you could expect its main file to reside in some sort of `ember-auth/source`, `ember/auth/source`, `ember-auth-source`, etc. In this case, it is `ember-auth/source`, so (as expected) one would `require 'ember-auth/source'` to load the gem. This is also how [`ember-auth-rails`](https://github.com/heartsentwined/ember-auth-rails/) accesses the source gem.

**Comment by lagartoflojo** [comment]
Oh, ok.
I thought it was strange, because with ember-source you have access to
Ember::Source immediately, without additional requires.
Thanks!

**Comment by heartsentwined** [comment]
I'm not sure which is the norm, because some gems, e.g. `squeel`, does need an additional `require`. I'll mark this as an enhancement.

**Comment by heartsentwined** [comment]
Implemented, although it does require a BC-breaking change. In `8.0.0`, the top-level namespace becomes `Ember::Auth`, and the load path becomes `(lib/)ember/auth`. Now you can do `Bundler.require`, and ember-auth will be available at `Ember::Auth::Source`. If you need a custom require statement, you'll need to `require 'ember/auth/source'` (not `ember-auth/source`).

Same happened to `ember-auth-rails`, at `5.0.1`. (`5.0.0` was yanked.)

**Comment by lagartoflojo** [comment]
Excellent! Thanks for this =)
