### ISSUE TITLE
route option for sign in

### ISSUE THREAD

**Issue by bseng** [heartsentwined/ember-auth#93]
I've been looking at the tutorial, docs and code but can't find anything related to the following scenario.

Let say User sign up, after creating account you want to redirect them to a setup wizard page, which is a once off process. Right now the only possible way is to write the logic in signInSuccess and transitionToRoute.

Can we have a route options in SignIn so SignIn can be more flexible?

Thanks

**Comment by heartsentwined** [comment]
Looks good - marked as enhancement. I'll code this when I have free time.

**Comment by bseng** [comment]
Thanks for your quick reply

**Comment by heartsentwined** [comment]
I have been thinking this through. What is your expected API for this use case?

A "sign up" function, _per se_, is not handled by `ember-auth`; it's just an ordinary call to the `create` endpoint of the user model. I guess that you are using the `App.Auth.createSession()` method to inject an authenticated session upon a successful server response, to mimic an auto-sign-in-after-sign-up function? In this case, I think the redirect logic should belong to where you have put the `createSession()` method.

I cannot get what you mean by the reference to `signIn`, perhaps you want a special sign in end point for a "freshly-created" account? In that case, #90 has been implemented, which allows you to do 

``` coffeescript
App.Auth.signIn '/custom/end/point', { opts: 'value' }
# the existing 
# App.Auth.signIn { opts: 'value' }
# would still work
```

**Comment by heartsentwined** [comment]
The original issue, if the assumption (due to inactivity) of using `createSession()` is correct, is solvable by 

``` coffeescript
@auth.createSession( /* data */ ).then ->
  # redirect here
```

This code snippet uses `9.x` branch syntax. The usual code-generating [docs](http://ember-auth.herokuapp.com/) and [upgrade guide](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide) to help with the transition.

Please reopen this ticket if it doesn't work, or if we have read the use case incorrectly.
